CREATE TABLE BOARD_DEF(
	BOARD_CD varchar2(50) PRIMARY KEY, 
	BOARD_NM varchar2(50)
);

CREATE TABLE POST(
	POST_NO int, 
	BOARD_CD varchar2(50),
	POST_SJ varchar2(50),
	POST_CN varchar2(50),
	REGSTR_ID varchar2(50),
	REG_DT DATE,
	CONSTRAINT POST_NO_BOARD_CD_PK PRIMARY KEY(POST_NO, BOARD_CD)
);

CREATE TABLE TAG(
	TAG_NO int PRIMARY KEY, 
	TAG varchar2(50),
	BOARD_CD varchar2(50)
);

CREATE TABLE POST_TAG(
	BOARD_TAG_ID int PRIMARY KEY, 
	POST_NO int,
	BOARD_Cd varchar2(50),
	TAG_ID int
);

DROP TABLE POST;

